contact_links:
  - name: Report a Security Vulnerability
    about: Please report security vulnerabilities privately so we can fix them before they are publicly disclosed. Report vulnerabilities personally by sending a dm to @stikyt on Discord
  - name: Request a Feature
    url: https://github.com/Operation-Eclipse/red-eclipse-14/discussions/new?category=ideas
    about: Submit feature requests on our Discussion forum or in Discord server (https://discord.gg/Ab9WzXJCmf).
