contact_links:
  - name: Report a Security Vulnerability
    url: Report vulnerabilities personally by sending a dm to @stikyt on Discord
    about: Please report security vulnerabilities privately so we can fix them before they are publicly disclosed.
  - name: Request a Feature
    url: https://discord.gg/Ab9WzXJCmf
    about: Submit feature requests on our Discord server (https://discord.gg/Ab9WzXJCmf).
